- go.mod
- go.sum
Previous goleveldb options that I modified was a little too much, increasing compaction time. Below are the changed options.
name|value
-- | --
TableSize | 2
TableSizeMult | 2
TotalSize | 20
TotalSizeMult | 10
level | 1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | -- | --
TableSize | 4 | 8 | 16 | 32 | 64 | 128
TotalSize | 200 | 2000 | 20000 | 200000 | 2000000 | 20000000
> tm-db: reduce the compaction time

- app/app.go
When we execute delegate, the staking module's power index logics are working with `validator` instance what we passed.
If we do not reload the `validator` instance, the logics are broken and it makes `Tendermint` to receive duplicate validator power update events.
> [Bugfix] Reload validator after delegation

- Dockerfile
use wamvm v1.0.0 when running build-linux
> use wasmvm 1.0.0

- app/app.go
Validator account can have vesting if they use classic addresses to make validator. If they make `gentx` with vesting tokens, the genesis staking steps will be failed because the tokens are already in use. 
To prevent that case, exclude validators from being genesis staking.
> exclude validator addresses from being genesis staking

- app/app.go
- app/const.go
- app/upgrade.go
An exchange with the wallet address `terra1chq5ps8yya004gsw4xz62pd4psr5hafe7kdt6d` was incorrectly whitelisted during Genesis. The whitelisted address in [genesis-tools](https://github.com/terra-money/genesis-tools/blob/main/src/exchange/terra_wallets.csv) was `terra1chq5ps8yya004gsw4xz62pd4psr5hafe7kdt6`, instead of the actual address which had the letter “d” at the end. This resulted in less unlocked LUNA at Genesis, and also subjected them to the longest vesting period.
~1.137M LUNA will be unlocked with this update, and the vesting schedule for the remaining LUNA will be adjusted to ‘6 month cliff, 2 year vesting’.
> add an exchange vesting schedule correction software upgrade

- .github/workflows/lint.yml
- .golangci.yml
- app/ante/ante_test.go
- app/ante/sigverify.go
- app/app.go
- app/export.go
- app/tx/broadcast.go
- client/docs/statik/init.go
- cmd/terrad/root.go
Hello Team,
Thanks @faddat for submitting the https://github.com/terra-money/core/pull/98 and @gregnuj  for reviewing the PR. Unfortunately we have to revert the PR since this other PR https://github.com/terra-money/core/pull/106 contains a major upgrade on core. 
The https://github.com/terra-money/core/pull/106 already contains the fixes for the linter and some of the files that were modified aren't existing anymore (app/ante/ante_test.go, app/ante/sigverify.go and app/tx/broadcast.go
). But please feel free to keep contributing any help is very welcome.
Reverts terra-money/core#98
> Revert "Cleanup"

- CHANGELOG.md
- RELEASES.md
- SECURITY.md
- readme.md
- scripts/tests/README.md
- scripts/tests/ibc-hooks/counter/README.md
* Update readme.md
* Update CHANGELOG.md
* Update RELEASES.md
* Update SECURITY.md
* Update README.md
* Update README.md
> Update markdown files (#123)

- app/app.go
- app/config/const.go
- app/upgrades/v2.4.0/upgrade.go
- app/upgrades/v2.4/upgrade.go
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- scripts/chain-upgrade-tester/chain-upgrade.sh
This pull request create the core upgrade function and  adds the new version number everywhere in the code
> feat: migration and version chaning

- app/app.go
- x/ibc-hooks/wasm_hook.go
IBC hooks wasn't triggering callbacks even when `memo` was set with the contract address. The issue was due to a misconfiguration of the transfer module not given the ICS4_middleware with IBC hooks included. 
Also fixed another bug in which memo did not excluded the key `ibc_callback` for backwards compatibility.
> fix: ibc-hooks callback not triggering wasm callback

- app/app.go
- custom/bank/keeper/hooks.go
- custom/bank/keeper/keeper.go
- custom/bank/module.go
- custom/bank/types/expected_hooks.go
- x/tokenfactory/keeper/before_send.go
- x/tokenfactory/keeper/keeper.go
This pull request implement BankHooks for TokenFactory
> feat: bank hooks

- app/app.go
On a previous commit (https://github.com/terra-money/core/commit/a511f8c133568f9ca7a774db0793c6a7379116cf)  the line of code SetModuleVersionMap was deleted by mistake. This causes an error when a new chain is created and wants to be updated because the module versions are not available to upgrade.
> feat: module version

- app/app.go
- app/config/const.go
Due to an incorrect plan name during the 2.4 upgrade, pisco upgrade to 2.5 will fail since the incorrect plan is not registered in this version.
Adding the handler here so that the check will pass.
> Fix/pisco upgrade 2.5

- app/app.go
- app/upgrades/v2.5/upgrade.go
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- scripts/protoc-swagger-gen.sh
- scripts/tests/alliance/delegate.sh
> fix: added pob queries to swagger and init module with default params

- Makefile
- app/app.go
- app/upgrades/v2.6/upgrade.go
Initiate feeshare module store and check if  POB account exists for pisco-1
> fix: v2.6 migrations

- app/app.go
- go.mod
- go.sum
Include [CosmWasm V0.43](https://github.com/CosmWasm/wasmd/tree/v0.43.0)
> feat: wasm v0.43

- app/keepers/keepers.go
With release 2.6 of core Wasmd was upgraded to the latest version including Wasmvm 1.4. 
This upgrade will enable all the new features. The choice to do it progressively is to make sure everything's still compatible before enabling the new features (in case a rollback is needed).
> feat: enable cosmwasm 1.4

- app/app.go
- app/app_test/app_test.go
- app/app_test/test_helpers.go
- app/export.go
- app/keepers/keepers.go
- app/keepers/keys.go
- app/modules.go
- app/simulation_test.go
- app/upgrade_handler.go
- x/feeshare/keeper/genesis_test.go
- x/feeshare/keeper/grpc_query_test.go
- x/feeshare/keeper/msg_server_test.go
- x/tokenfactory/bindings/custom_msg_test.go
- x/tokenfactory/bindings/custom_query_test.go
- x/tokenfactory/bindings/helpers_test.go
- x/tokenfactory/bindings/wasm.go
- x/tokenfactory/client/cli/query_test.go
- x/tokenfactory/keeper/before_send_test.go
- x/tokenfactory/keeper/createdenom_test.go
- x/tokenfactory/keeper/genesis_test.go
- x/tokenfactory/keeper/grpc_query_test.go
- x/tokenfactory/keeper/keeper_test.go
This pull request move Keepers, AppModules and AppUpgrade handlers to their own files that way app.go is more legible
> chore: core refact app

- go.mod
- go.sum
The new release from wasmd broke gov API compatibilty because proto gov/v1beta1 files were removed without migrating stored data to gov/v1 proto models. This pull request includes a fork of [wasmd](https://github.com/terra-money/wasmd/releases/tag/v0.43.0-terra) reverting the breaking changes PR https://github.com/CosmWasm/wasmd/pull/1646
> fix: wasmd using terra's fork

- integration-tests/src/modules/authz.test.ts
Tests to reproduce the issue with Authz when a validator has re-staking enabled.
> test(v2.7): authz test to reproduce feeshare bug

- go.mod
- go.sum
Use wasm [v0.45](https://github.com/CosmWasm/wasmd/blob/main/CHANGELOG.md) and [wasmvm v1.5.0](https://github.com/CosmWasm/cosmwasm/compare/v1.4.1...v1.5.0)
> feat(v2.8): use wasm v0.45 instead of terra's fork

- app/app.go
- app/keepers/keepers.go
Fix that updates the home directory to pass into the wasm module. This was causing mantlemint to check wasm cache in `$HOME/data/wasm` instead of `$NODE_HOME/data/wasm`
> fix: update wasm home dir

- app/config/const.go
- app/modules.go
- app/upgrade_handler.go
- app/upgrades/v2.8/upgrade.go
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- integration-tests/package-lock.json
- integration-tests/package.json
- scripts/tests/chain-upgrade/chain-upgrade.sh
Update release info and naming from 2.7 to 2.8 as the latest version
> chore(v2.8): prepare release

- readme.md
Changelog was pointing to main, fixed the changelog to point to v2.8, each time a new version is prepared this will have to be upgraded
> docs(v2.8): change README.md changelog URL

- go.mod
- go.sum
The previous POB mempool was allowing transactions to be included even though the sum of transactions gas requested was more than the block limit.
https://github.com/skip-mev/pob/compare/v1.0.4...v1.0.5
> fix: update pob mempool

- go.mod
- go.sum
Apply the WasmVM upgrade accordingly to the [CWA-2023-004.md](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-004.md#installing-the-patch) release.
> feat(v2.9): upgrade wasmvm

- go.mod
- go.sum
This PR reverts to the original version of IBC from 7.3.0 to the 7.3.1 from IBC go repo
> feat(v2.10): use original version of ibc-go 7.3.1 

- app/app.go
- integration-tests/src/modules/auth/auth.test.ts
`enforceStakingForVestingTokens` is a function that was used in the InitChainer when Phoenix-1 was bootstrapped that forced staking all vesting tokens, since this funcion is not needed anymore is better to clean this code with this new release
> feat(v2.10): remove vesting tokens code

- go.mod
- go.sum
- integration-tests/src/modules/gov/gov.test.ts
This will upgrade to fix the memory usage increases over time described here https://github.com/CosmWasm/cosmwasm/issues/1978. 
Full tag information available: https://github.com/CosmWasm/wasmvm/releases/tag/v1.5.2
It is also recommended to increase the `memory_cache_size` from the file `app.toml` to 1000MiB for mainnets and 500MiB for the testnets. Depending on the usage and amount of request, it will always be dependent on the validator:
```
[wasm]
memory_cache_size = 1000 # MiB
```
> feat(v2.9): upgrade wasmvm 1.5.2

- go.mod
- go.sum
This will upgrade to fix the memory usage increases over time described here https://github.com/CosmWasm/cosmwasm/issues/1978. 
Full tag information available: https://github.com/CosmWasm/wasmvm/releases/tag/v1.4.3
It is also recommended to increase the `memory_cache_size` from the file `app.toml` to 1000MiB for mainnets and 500MiB for the testnets. Depending on the usage and amount of request, it will always be dependent on the validator:
```
[wasm]
memory_cache_size = 1000 # MiB
```
> feat(v2.6): upgrade wasmvm 1.4.3

- app/upgrade_handler.go
- app/upgrades/v2.9/upgrade.go
Fix the following error for the v2.9 chain upgrade: 
`"failed to load latest version: version of store interchainquery mismatch root store's version; expected 8781999 got 0; new stores should be added using StoreUpgrades"`
> fix: icq store

- app/encoding_test.go
- app/genesis_test.go
- app/post/mocks/post_mock.go
- app/simulation_test.go
- cmd/terrad/config.go
- x/feeshare/post/post_test.go
Some typos with comments and organized imports
> fix formatting

- integration-tests/src/modules/alliance/alliance.test.ts
- integration-tests/src/modules/gov/gov.test.ts
- integration-tests/src/modules/tokenfactory/tokenfactory.test.ts
Some integration tests were missing the gas price and since the gas price was setup in the configuration we need to update the tests and x/token-factory module test was performing the beforeSendHooks with the wrong values.
> fix(v2.11): integration tests

- app/upgrade_handler.go
- app/upgrades/v2.9/upgrade.go
Fixes a typo for the upgrade handler
It's okay that the codecov does not work because we don't cover empty upgrde handlers
> fix(v2.10): upgrade handler

- integration-tests/package-lock.json
- integration-tests/package.json
- integration-tests/src/modules/smartaccount/pretx.test.ts
- x/smartaccount/ante/auth.go
- x/smartaccount/ante/pretransaction.go
- x/smartaccount/ante/tests/auth_test.go
- x/smartaccount/ante/tests/pretransaction_test.go
- x/smartaccount/keeper/msg_server_test.go
- x/smartaccount/post/posttransaction.go
- x/smartaccount/post/posttransaction_test.go
```
PASS  src/modules/smartaccount/pretx.test.ts (11.882 s)
Smartaccount Module (https://github.com/terra-money/core/tree/release/v2.6/x/smartaccount)
✓ Create new smart account (1245 ms)
✓ Deploy smart account limit contract (2496 ms)
✓ Update pre tx hooks (1214 ms)
✓ Transaction should fail for delegation (1209 ms)
✓ Transaction should pass for send (1217 ms)
```
> fix: get sa settings using ctx
